github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
bot:
  automerge: true
test: native_and_emulated